### ISSUE TITLE
onDeeplink function not triggering

### ISSUE THREAD

**Issue by lhilton** [TROPHiT/UnityDeeplinks#3]
I setup a new Unity project to play with this. I followed the readme, and I have the test app working so far as my scheme link on a test webpage opens the app. What I am not seeing is the onDeeplink function triggering in the UnityDeeplinks.cs code.

It looks like the Android side of this might have changed. Is the jar file based on the current codebase?

I did try running the build_jar.sh and had no errors, however I could no longer compile my Unity test app.

**Comment by lhilton** [comment]
Note: I was able to resolve the issue with rebuilding the jar, I was using the wrong version of the Java SDK. After setting to the right java version, I still retain this issue.

I am using an Application.Quit() to try to see when I've hit the onDeeplink on my test phone, it never seems to get his. This is my class:

`
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using UnityEngine.UI;

public class UnityDeeplinks : MonoBehaviour {
    public Text t;
	#if UNITY_IOS
	[DllImport("__Internal")]
	private static extern void UnityDeeplinks_init(string gameObject = null, string deeplinkMethod = null);
	#endif

	// Use this for initialization
	void Start () {
		#if UNITY_IOS
		if (Application.platform == RuntimePlatform.IPhonePlayer) {
			UnityDeeplinks_init(gameObject.name);
		}
		#endif
	}

	// Update is called once per frame
	void Update () {

	}

	public void onDeeplink(string deeplink) {
		Debug.Log("onDeeplink " + deeplink);

        Application.Quit();
	}


}
`

**Comment by lhilton** [comment]
**sigh**

Some days I get so close to knowing what I'm doing. I did not name the gameObject in my scene **UnityDeeplinks**, I had just left it the default name.

Closing as PEBKAC

**Comment by TROPHiT** [comment]
Thanks Lee, you can also use a different object name in case you can't change it - referring to the note section in the readme:

_"Optional: by default, MyUnityPlayerActivity calls a Unity script method onDeeplink on a game object called UnityDeeplinks. If you wish to change the name of the object or method, you should edit Assets/UnityDeeplinks/Android/MyUnityPlayerActivity.java, change the values of the gameObject and/or deeplinkMethod static properties and rebuild the UnityDeeplinks.jar file as instructed below"_
